### PR TITLE
Add view for scamper1 + hopannotation1 join

### PR DESCRIPTION
**Pull request by cristinaleonr**
Link to view in sandbox https://pantheon.corp.google.com/bigquery?project=mlab-sandbox&ws=!1m5!1m4!4m3!1smlab-sandbox!2sndt!3sscamper1_hopannotation1&d=ndt&p=mlab-sandbox&t=scamper1_hopannotation1&page=table

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
It would be useful to add a paragraph in the sql header providing a rough estimate of the cost of querying this view, in both GBytes and slot time.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108#-:-Mo9XFQ032icWmDmmGJL:b-umowaf)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[views/ndt/scamper1_hopannotation1.sql, line 9 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9WqgY7QZlIqlX9eZF:-Mo9WqgY7QZlIqlX9eZG:b6d7m0n) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L9)):*
> ```TSQL
> -- The schema uses the Standard Top-level Columns design.
> --
> -- This view is not intended to receive long term support by the M-Lab
> ```

I've been debating whether to use a prefix in struct names, to make it clearer that fields within the struct are experimental, or alpha or beta.  We could name the annotations struct exp_annotations, for example.  Thoughts?
___
*[views/ndt/scamper1_hopannotation1.sql, line 21 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9W2d26q2drePuL0Yx:-Mo9W2d26q2drePuL0Yy:b-xjpkwv) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L21)):*
> ```TSQL
> WITH scamper1 AS (
>     SELECT * FROM `{{.ProjectID}}.ndt.scamper1`
>     WHERE date BETWEEN "2021-11-01" AND "2021-11-07"
> ```

Change to use previous week, perhaps from 10 days ago to 3 days ago, so that it will generally have all data available.
BETWEEN DATE_DIFF(CURRENT_DATE(), 10 DAYS) ...
___
*[views/ndt/scamper1_hopannotation1.sql, line 34 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9WNhA4sw5agJKnKwA:-Mo9WNhA4sw5agJKnKwB:b4w95ot) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L34)):*
> ```TSQL
>     SELECT hops.id,
> 	STRUCT(hops.Hop.hop_id, hops.Hop.addr, hops.Hop.name, hops.Hop.q_ttl, hops.Hop.linkc, hops.Hop.links, ann.raw.Annotations AS annotations) as hop
>     FROM hops LEFT JOIN `{{.ProjectID}}.raw_ndt.hopannotation1` as ann ON (hops.hop.hop_id = ann.id)
> ```

Try adding the date=date restriction.  I think it will make it faster, since it won't have to search through all the partitions, but you can check.

Also would be interesting to know if the query is any faster if a single date is provided in the WHERE clause when querying the view.

**Review by gfr10598 — COMMENTED** [review]
Oh - looking good!  Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108#-:-Mo9XW8-9xmBEoUdSJBC:bz1kq0u)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[views/ndt/scamper1_hopannotation1.sql, line 9 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9WqgY7QZlIqlX9eZF:-MoKqXZv7w7ycBlfOZFm:b-1gcvqh) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L9)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I've been debating whether to use a prefix in struct names, to make it clearer that fields within the struct are experimental, or alpha or beta.  We could name the annotations struct exp_annotations, for example.  Thoughts?
</blockquote></details>

Sounds good. I added the "exp" prefix.
___
*[views/ndt/scamper1_hopannotation1.sql, line 21 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9W2d26q2drePuL0Yx:-MoKqlIk3VWjreR3bD7b:b-a2ujfy) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Change to use previous week, perhaps from 10 days ago to 3 days ago, so that it will generally have all data available.
BETWEEN DATE_DIFF(CURRENT_DATE(), 10 DAYS) ...

</blockquote></details>

Changed!
___
*[views/ndt/scamper1_hopannotation1.sql, line 34 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9WNhA4sw5agJKnKwA:-MoKqnE_B6a8DOnaop9x:b-s3egcy) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L34)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Try adding the date=date restriction.  I think it will make it faster, since it won't have to search through all the partitions, but you can check.

Also would be interesting to know if the query is any faster if a single date is provided in the WHERE clause when querying the view.
</blockquote></details>

Okay, I tried a few things out and these are the results:

**Using the previous week in the WHERE clause when creating the view**.
`date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)`.

|                                                                                                                                   | Bytes processed | Slot time consumed | Bytes shuffled | Bytes spilled to disk | Number of rows |
|-----------------------------------------------------------------------------------------------------------------------------------|-----------------|--------------------|----------------|-----------------------|----------------|
| Without specifying date                                                                                                           | 687.5 GB        | 4 days 1 hr        | 10.13 TB       | 2.14 TB               | 109,259,807    |
| With date in JOIN  (`hops.date = ann.date AND hops.hop.hop_id = ann.id`) | 661.2 GB        | 3 days 23 hr       | 10.09 TB       | 1.92 TB               | 109,259,807    |
| With date in WHERE (`WHERE hops.date = ann.date`)                                                                                   | 661.2 GB        | 3 days 16 hr       | 10 TB          | 2.02 TB               | 108,879,241    |


**Using a single date in the WHERE clause when creating the view**.
`date = DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)`.

|                                                                          | Bytes processed | Slot time consumed | Bytes shuffled | Bytes spilled to disk | Number of rows |
|--------------------------------------------------------------------------|-----------------|--------------------|----------------|-----------------------|----------------|
| Without specifying date                                                  | 113.3 GB        | 10 hr 31 min       | 1.16 TB        | 0 B                   | 14,173,683     |
| With date in JOIN  (`hops.date = ann.date AND hops.hop.hop_id = ann.id`) | 83.6 GB         | 14 hr 4 min        | 1.18 TB        | 0 B                   | 14,173,683     |
| With date in WHERE (`WHERE hops.date = ann.date`)                        | 83.6 GB         | 16 hr 33 min       | 1.18 TB        | 0 B                   | 14,117,456     |

From that, my main takeaways are that:
 * Using a single date instead of the whole week when querying the view is much cheaper, so we should probably do that if it's sufficient.
 * Adding a date=date restriction to the `JOIN` can produce a small improvement in terms of bytes processed.
 * Adding the date restriction to a WHERE drops a few rows, so we might not want to do that.

Let me know what you think!

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108#-:-Moj1LJW2IvTaO-CAJ7Z:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[views/create_dataset_views.sh, line 102 at r5](https://reviewable.io/reviews/m-lab/etl-schema/108#-Moj0tOU447pHD_XB7r5:-Moj0tOU447pHD_XB7r6:bwzz1ab) ([raw file](https://github.com/m-lab/etl-schema/blob/fe603373b6dd0d6b29c55faf83b18fbba0f65091/views/create_dataset_views.sh#L102)):*
> ```Shell
> create_view ${DST_PROJECT} ${DST_PROJECT} ndt ./ndt/unified_uploads_20201026x.sql
> create_view ${DST_PROJECT} ${DST_PROJECT} ndt ./ndt/unified_uploads.sql
> create_view ${SRC_PROJECT} ${DST_PROJECT} ndt ./ndt/scamper1_hopannotation1.sql
> ```

BTW, For future discussion, I wonder if we should have an ndt_exp dataset, that is expressly intended for experimental tables and views.  This view would be a good candidate.

I think initially we should put experimental views in both places for visibility and then use blog posts to make sure people are aware of the new dataset.
___
*[views/ndt/scamper1_hopannotation1.sql, line 34 at r3](https://reviewable.io/reviews/m-lab/etl-schema/108#-Mo9WNhA4sw5agJKnKwA:-Moj0G_Q0D6535BPUKKL:b-nl9u7n) ([raw file](https://github.com/m-lab/etl-schema/blob/ecd136f93300cdfdc9c7470bf92248d697d04d9c/views/ndt/scamper1_hopannotation1.sql#L34)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Okay, I tried a few things out and these are the results:

**Using the previous week in the WHERE clause when creating the view**.
`date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)`.

|                                                                                                                                   | Bytes processed | Slot time consumed | Bytes shuffled | Bytes spilled to disk | Number of rows |
|-----------------------------------------------------------------------------------------------------------------------------------|-----------------|--------------------|----------------|-----------------------|----------------|
| Without specifying date                                                                                                           | 687.5 GB        | 4 days 1 hr        | 10.13 TB       | 2.14 TB               | 109,259,807    |
| With date in JOIN  (`hops.date = ann.date AND hops.hop.hop_id = ann.id`) | 661.2 GB        | 3 days 23 hr       | 10.09 TB       | 1.92 TB               | 109,259,807    |
| With date in WHERE (`WHERE hops.date = ann.date`)                                                                                   | 661.2 GB        | 3 days 16 hr       | 10 TB          | 2.02 TB               | 108,879,241    |


**Using a single date in the WHERE clause when creating the view**.
`date = DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)`.

|                                                                          | Bytes processed | Slot time consumed | Bytes shuffled | Bytes spilled to disk | Number of rows |
|--------------------------------------------------------------------------|-----------------|--------------------|----------------|-----------------------|----------------|
| Without specifying date                                                  | 113.3 GB        | 10 hr 31 min       | 1.16 TB        | 0 B                   | 14,173,683     |
| With date in JOIN  (`hops.date = ann.date AND hops.hop.hop_id = ann.id`) | 83.6 GB         | 14 hr 4 min        | 1.18 TB        | 0 B                   | 14,173,683     |
| With date in WHERE (`WHERE hops.date = ann.date`)                        | 83.6 GB         | 16 hr 33 min       | 1.18 TB        | 0 B                   | 14,117,456     |

From that, my main takeaways are that:
 * Using a single date instead of the whole week when querying the view is much cheaper, so we should probably do that if it's sufficient.
 * Adding a date=date restriction to the `JOIN` can produce a small improvement in terms of bytes processed.
 * Adding the date restriction to a WHERE drops a few rows, so we might not want to do that.

Let me know what you think!





</blockquote></details>

This is great data!  Thanks!
___
*[views/ndt/scamper1_hopannotation1.sql, line 43 at r5](https://reviewable.io/reviews/m-lab/etl-schema/108#-Moj0Kvm-H3UnKXClWxl:-Moj0Kvm-H3UnKXClWxm:bx3zxlw) ([raw file](https://github.com/m-lab/etl-schema/blob/fe603373b6dd0d6b29c55faf83b18fbba0f65091/views/ndt/scamper1_hopannotation1.sql#L43)):*
> ```TSQL
> 
> -- Now reassemble the Hop arrays.
> mash AS (
> ```

I think this was my name for this subquery way back when.  Can you think of a better name?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[views/create_dataset_views.sh, line 102 at r5](https://reviewable.io/reviews/m-lab/etl-schema/108#-Moj0tOU447pHD_XB7r5:-MojuwCDDUrEU_L2_5Yo:b77vm36) ([raw file](https://github.com/m-lab/etl-schema/blob/fe603373b6dd0d6b29c55faf83b18fbba0f65091/views/create_dataset_views.sh#L102)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, For future discussion, I wonder if we should have an ndt_exp dataset, that is expressly intended for experimental tables and views.  This view would be a good candidate.

I think initially we should put experimental views in both places for visibility and then use blog posts to make sure people are aware of the new dataset.
</blockquote></details>

This is a good idea for the future!

@stephen-soltesz , fyi.
___
*[views/ndt/scamper1_hopannotation1.sql, line 43 at r5](https://reviewable.io/reviews/m-lab/etl-schema/108#-Moj0Kvm-H3UnKXClWxl:-MojvB3I1x7wm7_zhnrO:b-vgx68e) ([raw file](https://github.com/m-lab/etl-schema/blob/fe603373b6dd0d6b29c55faf83b18fbba0f65091/views/ndt/scamper1_hopannotation1.sql#L43)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this was my name for this subquery way back when.  Can you think of a better name?
</blockquote></details>

`aggregated`, `aggregated_hops` or `reaggregated`?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/108)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[views/ndt/scamper1_hopannotation1.sql, line 43 at r5](https://reviewable.io/reviews/m-lab/etl-schema/108#-Moj0Kvm-H3UnKXClWxl:-MondW1oEot6cj_LkH5Y:b3q05p) ([raw file](https://github.com/m-lab/etl-schema/blob/fe603373b6dd0d6b29c55faf83b18fbba0f65091/views/ndt/scamper1_hopannotation1.sql#L43)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

`aggregated`, `aggregated_hops` or `reaggregated`?
</blockquote></details>

Went with `aggregated` :).

**Pull request merged**
