### PR TITLE
Adds a synthetic column for our most common query.

### PR DESCRIPTION
**Pull request by pboothe**
Currently how things are set up in sandbox.

https://bigquery.cloud.google.com/table/mlab-sandbox:ndt.downloads

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/37)

### CODE REVIEW

**Comment by pboothe** [comment]
Made the changes @gfr10598 requested. Waiting for LGTM from @stephen-soltesz before proceeding.

**Comment by pboothe** [comment]
Revert this code change after https://github.com/m-lab/etl/issues/663 is fixed.

**Comment by stephen-soltesz** [comment]
[@Ya] This needs to be tagged to deploy to prod.

**Comment by stephen-soltesz** [comment]
@yachang ^

**Pull request merged**
