### PR TITLE
add customized wehe views

### PR DESCRIPTION
**Pull request by zeinabshmeis**
Add views to “wehe" that shows tests from “wehe_raw" which belong to the application clients with mobile network.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/169)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Hello! FYI, I get this error when I try to run the queries `Field name metadata does not exist in STRUCT<userID STRING, historyCount INT64, testID STRING, ...> at [2:43]`. Is there supposed to be a metadata field?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/169#-:-NiLgpLu2-sCXDQoD-cO:bkxsdb0)* status: 0 of 1 approvals obtained

**Comment by zeinabshmeis** [comment]
Yes, that is my bad. Fixed.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/169)* status: 0 of 1 approvals obtained (waiting on @zeinabshmeis)

___
*[`views/wehe/clientXputs1.sql` line 9 at r2](https://reviewable.io/reviews/m-lab/etl-schema/169#-Nia-qSfBj7JKuk4IzOq:-Nia-qSfBj7JKuk4IzOr:b-28xmvu) ([raw file](https://github.com/m-lab/etl-schema/blob/1fcff04f13f554fa48eb6a3cdf5d3215f4619781/views/wehe/clientXputs1.sql#L9)):*
> ```TSQL
> FROM `{{.ProjectID}}.wehe_raw.clientXputs1` as xput
> INNER JOIN `{{.ProjectID}}.wehe_raw.replayInfo1` as info
> ON xput.raw.userID = info.raw.userID AND CAST(xput.raw.historyCount AS INT64) = CAST(info.raw.historyCount AS INT64) AND xput.raw.testID = info.raw.testID
> ```

Because the base tables require a filter over the `date` column to be queried, you will need to add some joining on the date column (e.g., `AND xput.date = info.date`).

Out of curiosity, why are we joining on `raw.historyCount`?

The comment also applies to the query under `views/wehe/decisions1.sql`.

**Comment by zeinabshmeis** [comment]
I added the date to the join filter. Just to make sure, there is no need to add it to the WHERE filter as well, right?

For the historyCount, a user can perform one test over wifi and then over the mobile network. In order to identify those on wifi and mobile, I join over the history count.

In general, each row from any of the three tables is unique by the combination of the three field: userID, historyCount, and testID. Contrary to its name, the testID is not the id of the Wehe test but the replay of the test. Value 0 means these info or throughput belongs to the original application replay, and 1 means they belong to the control replay.

**Review by cristinaleonr — APPROVED** [review]
Right, the users will need to add a filter on the `date` to the `WHERE` clause when they query the view.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/169#-:-NieWZP16KXj5ZMjyZLH:b1p7gzv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @zeinabshmeis)

___
*[`views/wehe/clientXputs1.sql` line 4 at r3](https://reviewable.io/reviews/m-lab/etl-schema/169#-NieWpVH7hbNcG-AwKnN:-NieWpVH7hbNcG-AwKnO:b-2jvaxh) ([raw file](https://github.com/m-lab/etl-schema/blob/ff6699d9dc7636ea443e48c2782243619c332ae7/views/wehe/clientXputs1.sql#L4)):*
> ```TSQL
> -- This view shows clientXputs1 from raw wehe for users
> -- that are not CLI (userID does not start with @)
> -- and carried over mobile network
> ```

Nit: "and **are** carried over mobile network **.**"

**Pull request merged**
