### PR TITLE
Update ndt5 extended views

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the ndt5 extended views to use the updated v2 (standard column) schema in the ndt5 annotated tables.

This change replaces the reconstruction of the v2 server and client annotations with native `Geo` and `Network` records.

NOTE: the ndt5 table includes a summary record for upload measurements but the raw C2S results do not include MinRTT or LossRate metrics. So, the dependency on tcpinfo is preserved here and for the other extended filter columns for now.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/112)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Part of:

* https://github.com/m-lab/etl/issues/1046

**Review by mattmathis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/112)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[views/ndt_intermediate/extended_ndt5_downloads.sql, line 116 at r3](https://reviewable.io/reviews/m-lab/etl-schema/112#-MuQx-tJ00pPTC9IfDRU:-MuQx-tK8czx4bQkbK9_:b-uq1hni) ([raw file](https://github.com/m-lab/etl-schema/blob/d2b89f43a69a95e567b14ec8348ddcc7daa68773/views/ndt_intermediate/extended_ndt5_downloads.sql#L116)):*
> ```TSQL
>       server.Network
>     ) AS server,
>     PreCleanNDT5 AS _internal202010  -- Not stable and subject to breaking changes
> ```

Update date code to force a breaking change on anybody using these fields.
___
*[views/ndt_intermediate/extended_ndt5_uploads.sql, line 109 at r3](https://reviewable.io/reviews/m-lab/etl-schema/112#-MuQzWw58URjd2Xg59d3:-MuQzWw58URjd2Xg59d4:b-uq1hni) ([raw file](https://github.com/m-lab/etl-schema/blob/d2b89f43a69a95e567b14ec8348ddcc7daa68773/views/ndt_intermediate/extended_ndt5_uploads.sql#L109)):*
> ```TSQL
>       server.Network
>     ) AS server,
>     PreCleanNDT5 AS _internal202010  -- Not stable and subject to breaking changes
> ```

Update date code to force a breaking change on anybody using these fields.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you, PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/112#-:-MuR65yl3RgQtijIcXZU:bxryuc8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[views/ndt_intermediate/extended_ndt5_downloads.sql, line 116 at r3](https://reviewable.io/reviews/m-lab/etl-schema/112#-MuQx-tJ00pPTC9IfDRU:-MuR5y26CcAeJE0qqKWg:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/d2b89f43a69a95e567b14ec8348ddcc7daa68773/views/ndt_intermediate/extended_ndt5_downloads.sql#L116)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

Update date code to force a breaking change on anybody using these fields.
</blockquote></details>

Done.
___
*[views/ndt_intermediate/extended_ndt5_uploads.sql, line 109 at r3](https://reviewable.io/reviews/m-lab/etl-schema/112#-MuQzWw58URjd2Xg59d3:-MuR63m-0Ddh5o6kMXtT:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/d2b89f43a69a95e567b14ec8348ddcc7daa68773/views/ndt_intermediate/extended_ndt5_uploads.sql#L109)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

Update date code to force a breaking change on anybody using these fields.
</blockquote></details>

Done.

**Review by mattmathis — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/112)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattmathis)

**Comment by stephen-soltesz** [comment]
(waiting to merge until ndt5 v2 parser makes one historical complete cycle)

**Comment by stephen-soltesz** [comment]
Okay we are up to date. This change can be deployed next week.

**Pull request merged**
