### PR TITLE
Replace aggregate dataset with traceroute

### PR DESCRIPTION
**Pull request by cristinaleonr**
New dataset https://pantheon.corp.google.com/bigquery?project=mlab-sandbox&d=traceroute&p=mlab-sandbox&page=dataset&ws=!1m14!1m3!3m2!1smlab-sandbox!2straceroute!1m4!4m3!1smlab-sandbox!2straceroute!3sparis1_legacy!1m4!4m3!1smlab-sandbox!2straceroute!3sscamper1

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/132)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Thank you!

What steps or commands did you use to create the dataset in BigQuery?

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/132#-:-N-PC3Kr5JzrygRfQP7y:bwbol7k)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[views/traceroute/paris1_legacy.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBiVh4p-Sfun4booD:-N-PBiVh4p-Sfun4booE:bzd0nns) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/paris1_legacy.sql#L1)):*
> ```TSQL
> -- This is the aggregated paris1 view.
> ```

```
-- This is the aggregated paris1 view from the web100 platform.
-- This includes measurements to ndt and all other measurement services.
```

Or similar. The "paris" data is pre-aggregated for all services on the old web100 platform.



_Code quote:_
```TSQL
-- This is the aggregated paris1 view.
-- Currenlty, it only contains data from ndt.
-- In the future, it can be combined with other experiments.
```
___
*[views/traceroute/scamper1.sql, line 2 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBfBg9j7VtTTYePKv:-N-PBfBg9j7VtTTYePKw:b-kqcw9) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/scamper1.sql#L2)):*
> ```TSQL
> -- This is the aggregated scamper1 view.
> -- Currenlty, it only contains data from ndt.
> ```

typo: Currently.
___
*[views/traceroute/scamper1.sql, line 5 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBXUJ1r5P0qLDsU8S:-N-PBXUJ1r5P0qLDsU8T:btfw2dj) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/scamper1.sql#L5)):*
> ```TSQL
> -- In the future, it can be combined with other experiments.
> --
> SELECT * FROM `{{.ProjectID}}.raw_ndt.scamper1`
> ```

Prefer `ndt.scamper1` to include the annotated rows?

**Review by cristinaleonr — COMMENTED** [review]
It was automatically created when I pushed to sandbox.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/132#-:-N-PEfyxBC40enMvqMds:b-xrba0q)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[views/traceroute/paris1_legacy.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBiVh4p-Sfun4booD:-N-PEcal5_NyKyBdVWGk:b-bw8e14) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/paris1_legacy.sql#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

```
-- This is the aggregated paris1 view from the web100 platform.
-- This includes measurements to ndt and all other measurement services.
```

Or similar. The "paris" data is pre-aggregated for all services on the old web100 platform.

</blockquote></details>

Updated.
___
*[views/traceroute/scamper1.sql, line 2 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBfBg9j7VtTTYePKv:-N-PER3p754CTvvzg-ow:b-rst3ay) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/scamper1.sql#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

typo: Currently.
</blockquote></details>

Sorry, fixed.
___
*[views/traceroute/scamper1.sql, line 5 at r1](https://reviewable.io/reviews/m-lab/etl-schema/132#-N-PBXUJ1r5P0qLDsU8S:-N-PEPu66fSxC7HLxdJ-:b-bw8e14) ([raw file](https://github.com/m-lab/etl-schema/blob/5c2886c66a4fb951b8287cadc3f82b5906a25465/views/traceroute/scamper1.sql#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Prefer `ndt.scamper1` to include the annotated rows?
</blockquote></details>

Updated.

**Review by stephen-soltesz — APPROVED** [review]
No kidding. I didn't know it did that!

:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/132#-:-N-PGOHu69cL4Uhb7fEf:b-kzr33g)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
@stephen-soltesz update, it did not automatically create the dataset in `measurement-lab` (but it did in sandbox, staging, and oti). 

It failed with this error: "Step #2: 2022/04/25 18:11:55 Failed to sync dataset: "traceroute" (error: googleapi: Error 403: Access Denied: Project measurement-lab: User does not have bigquery.datasets.create permission in project measurement-lab., accessDenied)"

I had to click on the three dots next to the project and select "Create dataset."

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/132#-:-N0XpElc1jcjs5C0NMn-:b-bizf4d)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
