### PR TITLE
Add 1.18 suffix to golang-cbif

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/144)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Looks like the Cloudbuild is failing now.

**Comment by SaiedKazemi** [comment]
@stephen-soltesz I double-checked the changes I made for Go 1.18 upgrade and didn't find anything to explain Cloud Build's failure.  Also, I have no idea why we see the old tag `v3.15.2+incompatible` when line 17 of the logs shows:
```
HEAD is now at 207dcfe Change "go get" to "go install"
```
Assigning this to you per our conversation.

**Review by stephen-soltesz — COMMENTED** [review]
This works:

```
go install -v ./cmd/bq_create_view
```

I will need to research more to understand exactly what steps `go` is taking now that are different from before. Originally, the `GOPATH=/go` used the local sources under `/go/src/github.com/m-lab/etl-schema/...` for the `go get` command. Now, I suspect that the `go install ...@latest` is fetching the version upstream.. though I'm still unclear why it's picking v3.15.2 since the most recent version is v3.42.0 on the repo... Providing the relative path to `go install` asks it to run on the files explicitly from this repo.

Does this work for you @saiedkazemi ?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/144#-:-N9quzCs2Cf0q98cwJt9:b-4gs7g4)* status: 0 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Is this PR still relevant? What remains to complete it?

**Comment by stephen-soltesz** [comment]
Hand off to @stephen-soltesz

**Pull request closed without merging**
