### PR TITLE
Add 'legacy' view for paris-traceroute

### PR DESCRIPTION
**Pull request by cristinaleonr**
The legacy-scamper rows have been removed from the traceroute table in sandbox through this query:
`DELETE FROM `mlab-sandbox.base_tables.traceroute`
WHERE scamper_version != ""`

This PR add an etl-schema “paris_legacy” view to measurement-lab to refer to {{.ProjectID}}.base_tables.traceroute (which contains only `paris-traceroute` rows).

Verification:
Screenshot 2022-02-28 10 56 54 AM

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/118)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
I think `paris1_legacy` is a better name than `traceroute_legacy` we said we'd use in https://www.measurementlab.net/blog/v2-data-pipeline-migration/ - since `paris1` is the underlying datatype we're going with. So, I'd like to publish an update to the blog, I'll send that to you for review. https://github.com/m-lab/website/pull/684

It's also possible to create the other `traceroute.paris1_legacy` view now.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/118#-:-Mx0CA4K7a9S16f0ty7O:b-dtw94h)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[views/ndt_raw/paris_legacy.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/118#-Mx0NcEcBWWZERrVt4mq:-Mx0NcEcBWWZERrVt4mr:b-auhfwe) ([raw file](https://github.com/m-lab/etl-schema/blob/0b4b63c12eafe83d10f9c8c94c16fd81bdcd08d7/views/ndt_raw/paris_legacy.sql#L1)):*
> ```TSQL
> #standardSQL
> ```

Please rename file to `paris1_legacy`.

**Review by cristinaleonr — COMMENTED** [review]
Changed. I also approved your PR.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/118#-:-Mx0YfSX-Pj3cNkqCL8O:b1jduiv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[views/ndt_raw/paris_legacy.sql, line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/118#-Mx0NcEcBWWZERrVt4mq:-Mx0Ye4ZEo2yK8MZuvMp:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/0b4b63c12eafe83d10f9c8c94c16fd81bdcd08d7/views/ndt_raw/paris_legacy.sql#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please rename file to `paris1_legacy`.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
Thank you - I verified the sandbox table appears to have no "legacy-scamper1" rows. This is a manual step to be run in every project? Now that we have a replacement for `traceroute_legacy` - there are a few additional steps to update references in prometheus-support bqx queries and remove that file from this repo.

:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/118#-:-Mx0amESBW6mV6FARJRX:bb2tud8)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Yes, it will also be run in staging and oti.

I will delete `traceroute_legacy` in the next PR.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/118#-:-Mx0d9zS9N-sgl2M956B:b50riho)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
