### PR TITLE
Fast unified views with exposed filter logic

### PR DESCRIPTION
**Pull request by mattmathis**
This has only been lightly tested, and will be the starting point for
more thurough testing and review.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
This looks really cool.

My comments are mostly style and consistency.

If there's any way we could complete  `-- TODO(https://github.com/m-lab/etl-schema/issues/141) Relocate IP and port` now, I would be grateful.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139#-:-N7Nj__2BBK_f5QJJpw9:b-9onlzm)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[`views/ndt/unified_downloads.sql` line 1 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NfOUv4FZa-yedHlyG:-N7NfOUv4FZa-yedHlyH:b-v4vw62) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt/unified_downloads.sql#L1)):*
> ```TSQL
> -- XXX **** This is a lightly tested prototype for new filter columns ****
> ```

Does this still belong here?
___
*[`views/ndt/unified_downloads.sql` line 27 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7Nfo-e5p9piw7HHVl-:-N7Nfo-e5p9piw7HHVl0:b-46akfm) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt/unified_downloads.sql#L27)):*
> ```TSQL
> -- are strongly encouraged to copy the Unified Extended subquery below
> -- as a private subquery or save it as a private Custom Unified Views
> -- (requires a BQ account) and edit them to fill their needs.
> ```

Are there links to additional information / instructions? Or a place holder..
___
*[`views/ndt/unified_downloads.sql` line 48 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7Ne_uhBGpGJ12uo9Xq:-N7Ne_uhBGpGJ12uo9Xr:bxxhe6n) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt/unified_downloads.sql#L48)):*
> ```TSQL
>     -- Studying internet performance
>     (
>       filter.IsComplete # Not missing any important fields
> ```

nit: please prefer `--` for comments throughout. More environments treat this consistently as a comment for SQL documents.
___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 45 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NiQne1ghP1O_-LlDB:-N7NiQne1ghP1O_-LlDC:big9a16) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L45)):*
> ```TSQL
>       CASE raw.ServerPort
>         WHEN 443 THEN "-WSS"
>         WHEN 80 THEN "-WS"
> ```

Hmm.. also we should make ndt7 record this directly.. guessing by ports isn't great. https://github.com/m-lab/ndt-server/issues/359 
___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 46 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7Ni-483DPqN0nC85Cx:-N7Ni-490NB17fiNiYXE:b71qozt) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L46)):*
> ```TSQL
>         WHEN 443 THEN "-WSS"
>         WHEN 80 THEN "-WS"
>         ELSE "-UNK" END ) AS Protocol,
> ```

Do you see the UNK case? Either way, I would prefer that be a real word. UNK is not a generally recognized acronym. 
___
*[`views/ndt_intermediate/extended_web100_downloads.sql` line 38 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NcKYe0ZbFN3Tq1-MD:-N7NcKYe0ZbFN3Tq1-ME:b-1ebpmo) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_downloads.sql#L38)):*
> ```TSQL
>     False AS IsError,
> 
>     raw.web100.snap.Duration/1000.0 AS connection_duration, -- SYN to final snap time (includes setup)
> ```

For upload you used `raw.web100.snap.Duration*0.001`. I don't have a preference for either style. But please use the same convention throughout.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 50 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NaQH96bJEo2T129_G:-N7NaQH96bJEo2T129_H:b-3hyzup) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L50)):*
> ```TSQL
> 
>     -- Modernize Client and Server Metadata
>     [ -- STRUCT('client_af', raw.connection.client_af ) -- int not supported
> ```

The key values are all strings. This could be cast/formated as a string if desired.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 133 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NbdZx94ekBRQnu7cg:-N7Nbawn68T8qFjtqIAs:b-bnx9ha) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L133)):*
> ```TSQL
>     STRUCT (
>       -- TODO(https://github.com/m-lab/etl-schema/issues/141) Relocate IP and port
>       raw.web100.connection_spec.remote_ip AS IP,
> ```

Any chance we could do away with this now? The query code becomes just a pass-through of `client.Geo` in this case.

**Review by mattmathis — COMMENTED** [review]
For my next iteration of unified views, I want to do all of the additions for client IP privacy: ACLs, heavy hitter filtering, etc which will eliminate most uses cases IP address.   Doing a breaking change at that point encourages any users to transition to better solutions.

I plan to abandon this draft PR, and create a new clean one.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139#-:-N84zBnd09g2XRKfJAE-:bruhxd)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`views/ndt/unified_downloads.sql` line 1 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NfOUv4FZa-yedHlyG:-N84p2HFEUhMSn2HouX5:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt/unified_downloads.sql#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this still belong here?
</blockquote></details>

Done.
___
*[`views/ndt/unified_downloads.sql` line 27 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7Nfo-e5p9piw7HHVl-:-N84rL8tEXiVpcj4O4La:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt/unified_downloads.sql#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are there links to additional information / instructions? Or a place holder..
</blockquote></details>

Done.
___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 45 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NiQne1ghP1O_-LlDB:-N84tAfx67NHBRPVAmxD:btrp51l) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm.. also we should make ndt7 record this directly.. guessing by ports isn't great. https://github.com/m-lab/ndt-server/issues/359 
</blockquote></details>

Except the server determines the protocol by the port: SSL to port 80 and plaintext to port 443 should both fail
___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 46 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7Ni-483DPqN0nC85Cx:-N84u2ja9pwfq654oHRn:bhvkjhk) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L46)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do you see the UNK case? Either way, I would prefer that be a real word. UNK is not a generally recognized acronym. 
</blockquote></details>

I don't believe so for ndt7.   This logic will need to be updated if we ever do something weird, like running SSL on non-standard ports.   If we need to make protocol and port independent, we still need to expose both (carry both fields here).
___
*[`views/ndt_intermediate/extended_web100_downloads.sql` line 38 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NcKYe0ZbFN3Tq1-MD:-N84vFw86HhHasBxs_dY:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_downloads.sql#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

For upload you used `raw.web100.snap.Duration*0.001`. I don't have a preference for either style. But please use the same convention throughout.
</blockquote></details>

Done.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 50 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NaQH96bJEo2T129_G:-N84wlw97Xdmw9DMlXAC:b90ynn8) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The key values are all strings. This could be cast/formated as a string if desired.
</blockquote></details>

I prototyped a version that used ascii encoded KVP for metadata, but it was not easier to parse in downstream SQL or python.  After testing it for a bit, I went back to the traditional BQ array of structs.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 133 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NbdZx94ekBRQnu7cg:-N84xvyB7KyVJXQ3h8V5:b-5z5zs8) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L133)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Any chance we could do away with this now? The query code becomes just a pass-through of `client.Geo` in this case.
</blockquote></details>

This would be a breaking change for some users, which is out of scope for this update.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 2 of 8 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 45 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NiQne1ghP1O_-LlDB:-N858ZVj9Sdyq-Mbasim:b-uaxf8s) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L45)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

Except the server determines the protocol by the port: SSL to port 80 and plaintext to port 443 should both fail
</blockquote></details>

We could imagine running on alternate ports. Better for the server to record the protocol at archival time I think, so this inference is unnecessary.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 50 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NaQH96bJEo2T129_G:-N859Fn86-K9fgGEYKKJ:bdrpksr) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L50)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

I prototyped a version that used ascii encoded KVP for metadata, but it was not easier to parse in downstream SQL or python.  After testing it for a bit, I went back to the traditional BQ array of structs.
</blockquote></details>

Are we talking about the same thing?

client_af could be included here as a string rather than int.

Is this desirable? If it is, then we can do that here. If it's not needed, then the commented logic can be removed.



_Code quote:_
```TSQL
-- STRUCT('client_af', raw.connection.client_af ) -- int not supported
```

**Comment by stephen-soltesz** [comment]
(if you'd not said that you were abandoning this PR, I could have said it lgtm -- I'm not sure what else you have planned though)

**Review by mattmathis — COMMENTED** [review]
I was going to clean up the history, but I will do that in the squash merge instead.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139#-:-N85reZaBLcmpeiJ-6bz:bn8lecw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 45 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NiQne1ghP1O_-LlDB:-N85s5Ud5pCSo2E-uDUq:b-jawgun) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We could imagine running on alternate ports. Better for the server to record the protocol at archival time I think, so this inference is unnecessary.
</blockquote></details>

I agree it would be better do do this more explicitly in the server, but right now we don't have that and users sometimes need to know.
___
*[`views/ndt_intermediate/extended_web100_uploads.sql` line 50 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NaQH96bJEo2T129_G:-N85rDR88UwS9UG5zUZu:b7vdsqw) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_web100_uploads.sql#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are we talking about the same thing?

client_af could be included here as a string rather than int.

Is this desirable? If it is, then we can do that here. If it's not needed, then the commented logic can be removed.
</blockquote></details>

DONE Unneeded comment removed.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/139#-:-N85uL_F8NJQ2dlwKOf1:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`views/ndt_intermediate/extended_ndt7_downloads.sql` line 45 at r2](https://reviewable.io/reviews/m-lab/etl-schema/139#-N7NiQne1ghP1O_-LlDB:-N85u5CY27nxMy_obN8i:bpeslfg) ([raw file](https://github.com/m-lab/etl-schema/blob/eda38dd9d46e92683a9dc36b13f637ebae302caf/views/ndt_intermediate/extended_ndt7_downloads.sql#L45)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

I agree it would be better do do this more explicitly in the server, but right now we don't have that and users sometimes need to know.
</blockquote></details>

All good. My comment wasn't meant to object to what you were doing here out of necessity, but to comment generally on a preferable way.

**Pull request merged**
