### PR TITLE
Add support for deploying Table Functions

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds support for adding and deploying [BigQuery Table Functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_function_statement)

The first table function is to back Grafana dashboards for ndt7 performance distributions. However, this change should establish a convention that allows us to add more table functions in the future for various operational tasks or other dashboards.

Note: these views are not intended for public use at this time. If that becomes helpful, we should create a new dataset designed for that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/160)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/160)* status: 0 of 1 approvals obtained (waiting on @laiyi-ohlsen and @stephen-soltesz)

___
*[`functions/ops.ndt7_download_pdf.sql` line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXut1dnBy1Y9PlTcnBm:-NXut1dnBy1Y9PlTcnBn:b-58gdop) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/ops.ndt7_download_pdf.sql#L1)):*
> ```TSQL
> -- Create the ops dtaset if it does not exist.
> ```

dataset*
___
*[`functions/ops.ndt7_download_pdf.sql` line 58 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXut6X_2TjN_imCGNYn:-NXut6X_2TjN_imCGNYo:b-muyj9c) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/ops.ndt7_download_pdf.sql#L58)):*
> ```TSQL
>       site,
>       bin_count,
>       -- Divide bin count by total number of samples for this site, to normalize counts all sites.
> ```

counts **for** all sites?
___
*[`functions/README.md` line 11 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXus_0NAWZO0Lyw5Yig:-NXus_0OE6c_oNxTRrRB:b-9xw89i) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/README.md#L11)):*
> ```Markdown
> must not collide with an existing table or view name.
> 
> The SQL file should defines the dataset name and table function. To prevent
> ```

define*
___
*[`functions/README.md` line 16 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXusn1eCbPHimthzdsQ:-NXusn1eCbPHimthzdsR:b-jvuoi0) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/README.md#L16)):*
> ```Markdown
> 
> * If the target dataset and table name is `ops.ndt7_download.pdf`, then the
>   configuration file should be named `ops.ndt7_download_pdf.sql`.
> ```

Should this be `ops.ndt7_download.pdf.sql`?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/160)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @laiyi-ohlsen)

___
*[`functions/ops.ndt7_download_pdf.sql` line 1 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXut1dnBy1Y9PlTcnBm:-NXuu8ZF6PGkTDXNPzuX:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/ops.ndt7_download_pdf.sql#L1)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

dataset*
</blockquote></details>

Done.
___
*[`functions/ops.ndt7_download_pdf.sql` line 58 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXut6X_2TjN_imCGNYn:-NXuuTEmEKMCbxZ5P3ik:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/ops.ndt7_download_pdf.sql#L58)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

counts **for** all sites?
</blockquote></details>

Done.
___
*[`functions/README.md` line 11 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXus_0NAWZO0Lyw5Yig:-NXuuWf63Rz9kvgQGyLQ:b-896fix) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/README.md#L11)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

define*
</blockquote></details>

Done.
___
*[`functions/README.md` line 16 at r1](https://reviewable.io/reviews/m-lab/etl-schema/160#-NXusn1eCbPHimthzdsQ:-NXuuWxE5nnPOna9XC1b:b-xwnuyy) ([raw file](https://github.com/m-lab/etl-schema/blob/c207f6873dcc53d4629235306aea502957c0b9cc/functions/README.md#L16)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be `ops.ndt7_download.pdf.sql`?
</blockquote></details>

The first one had a typo. It should have read `ops.ndt7_download_pdf`. Now fixed. My fingers want to turn that into an extension.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/160#-:-NXuvOec983397Tao2u5:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @laiyi-ohlsen)

**Comment by stephen-soltesz** [comment]
I'd like to merge this and add a second PR for uploads.

**Pull request merged**
